[package]
name = "bitcoin_handshake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
rand = "0.8.5"
sha2 = "0.10.8"
tokio = { version = "1.34", features = ["full"] }
